---
- name: Shoot mock users into DB
  community.mysql.mysql_query:
    login_db: totallyChatGPT
    login_user: "{{ db_user }}"
    login_password: "{{ db_token }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    query: INSERT INTO users (email, name, password_hash) VALUES (%s, %s, %s)
    positional_args:
      - "{{ item.email }}"
      - "{{ item.name }}"
      - "{{ item.password_hash }}"
  loop:
    - email: "{{ inserted_user1_email }}"
      name: Long Island Pete
      password_hash: "{{ inserted_user1_token }}"
    - email: "{{ inserted_user2_email }}"
      name: Vasco Sminem
      password_hash: "{{ inserted_user2_token }}"
    - email: "{{ inserted_user3_email }}"
      name: Yakub the Scholar
      password_hash: "{{ inserted_user3_token }}"
  no_log: true
