---
db_name: totallyChatGPT
db_user: "{{ vault_db_user }}"
db_token: "{{ vault_db_password }}"
ansible_user: "{{ vault_ansible_user }}"
inserted_user1_email: "{{ vault_insertedUser1_email }}"
inserted_user1_token: "{{ vault_insertedUser1_token }}"
inserted_user2_email: "{{ vault_insertedUser2_email }}"
inserted_user2_token: "{{ vault_insertedUser3_token }}"
inserted_user3_email: "{{ vault_insertedUser3_email }}"
inserted_user3_token: "{{ vault_insertedUser3_token }}"