---
- name: Ensure we've got python3-packaging
  ansible.builtin.package:
    name: python3-packaging
    state: present

- name: Ensure we've got pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Validate PyMySql is installed
  ansible.builtin.pip:
    name: PyMySql
    state: present

- name: Ensure MariaDB is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Ensure database exists
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Check if schema exists
  community.mysql.mysql_query:
    login_db: "{{ db_name }}"
    query: "SHOW TABLES LIKE 'shitty_pasta'"
    login_unix_socket: /var/lib/mysql/mysql.sock
  register: db_servers_tables_check

- name: Apply the schema
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: import
    target: files/template_schema.sql
    login_unix_socket: /var/lib/mysql/mysql.sock
  when: db_servers_tables_check.query_result[0] | length == 0
  delegate_to: localhost

- name: Create an app DB user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_token }}"
    priv: "{{ db_name }}.*:SELECT,INSERT,UPDATE,DELETE"
    host: localhost
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock
  no_log: true
